
title: Software Developer
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Jury Ghidinelli  ## put your name
title: 'Software Developer'  ## your title
location: Brescia, IT


## Social Profiles
facebook: https://www.facebook.com/jury.ghidinelli  ## your facebook account url
twitter: https://twitter.com/juryghidinelli  ## your twitter account url
linkedin: https://www.linkedin.com/in/juryghidinelli/  ## your linkedin account url
github: https://github.com/juryghidinelli  ## you dribbble account url
instagram: https://www.instagram.com/juryghidinelli  ## your foursquare account url
