title: APPLICAZIONI
skills:
  - name: Adobe Photoshop
    perc: 60

  - name: Adobe Lightroom
    perc: 65

  - name: Pentaho BI Suite
    perc: 70

  - name: Libreoffice
    perc: 90

  - name: Microsoft Excel
    perc: 90

  - name: Microsoft Word
    perc: 80

  - name: Microsoft Access
    perc: 90

  - name: Microsoft PowerBI
    perc: 60

  - name: Blender
    perc: 60

